version: '3'
services:
  web:
    build: .
    image: shvadart/about_me_with_com:latest
    ports:
      - '8080:8080'
      - '3000:3000'
    volumes:
      - ./comments.json:/usr/src/app/comments.json